services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - TZ
      - POSTGRES_USER=admin 
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=modular_monolith
    volumes:
      - ./docker_data/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - docker-web

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - docker-web

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      - REDIS_PASSWORD=admin
      - REDISPORT=6379
      - REDISSTACK_ENABLED=true
    restart: always
    networks:
      - docker-web
  
  # redisinsight:
  #   image: redis/redisinsight:latest
  #   container_name: redisinsight
  #   ports:
  #     - "5540:5540"
  #   environment:
  #     - RIPORT=${RIPORT:-5540}
  #     - RITRUSTEDORIGINS=http://localhost:9000
  #   depends_on:
  #     - redis
  #   restart: always
  #   networks:
  #     - docker-web

networks:
  docker-web:
    driver: bridge
